language: node_js
node_js:
  - "6.11.0"
install:
  - npm install -g firebase-tools
  - npm install
  - npm run webpack
scripts:
  - npm run test
after_success:
  - firebase deploy --token $FIREBASE_TOKEN